<a href="https://colab.research.google.com/github/lamiaessam/patchi_dashboard/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np

In [22]:
excel_sheet ='/content/Data model.xlsx'
sheets_location =pd.read_excel(excel_sheet,sheet_name=None)

In [23]:
sales = sheets_location['factSalesTable']
customer = sheets_location['dimCustomerTable']
product = sheets_location['dimProductTable']
product_category = sheets_location['dimProductCategoryTable']
product_subcategory = sheets_location['dimProductSubcategoryTable']
calender = sheets_location['dimDateTable']
region = sheets_location['dimRegionTable']

In [24]:
df_merge = pd.merge(sales,customer,on='CustomerKey',how='left')

In [25]:
df_merge =pd.merge(df_merge,region,on='GeographyKey',how='left')

In [26]:
df_merge = pd.merge(df_merge,product,on='ProductKey',how='left')

In [27]:
df_merge = pd.merge(df_merge,product_subcategory,on='ProductSubcategoryKey',how='left')

In [28]:
df_merge = pd.merge(df_merge,product_category,on='ProductCategoryKey',how='left')

In [29]:
df_merge = pd.merge(df_merge,calender,left_on='OrderDateKey',right_on='DateKey',how='left')

In [30]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114390 entries, 0 to 114389
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   ProductKey              114390 non-null  int64
 1   OrderDateKey            114390 non-null  int64
 2   CustomerKey             114390 non-null  int64
 3   Gender_x                0 non-null       float64
 4   OrderNumber             114390 non-null  int64
 5   OrderQuantity           114390 non-null  int64
 6   List Price              114390 non-null  float64
 7   Product Cost            114390 non-null  float64
 8   GeographyKey            63738 non-null   float64
 9   MaritalStatus           63738 non-null   object
 10  Gender_y                63738 non-null   object
 11  CustomerName            63738 non-null   object
 12  City                    63738 non-null   object
 13  Region                  63738 non-null   object
 14  Country                 63738 non-null   object
 15  ProductSubcategoryKey   114390 non-null  int64
 16  Color                   59400 non-null   object
 17  StandardCost            114390 non-null  float64
 18  ListPrice               114390 non-null  float64
 19  Product Name            114390 non-null  object
 20  ProductSubcategoryName  114390 non-null  object
 21  ProductCategoryKey      114390 non-null  int64
 22  ProductCategoryName     114390 non-null  object
 23  DateKey                 114390 non-null  int64
 24  FullDateAlternateKey    114390 non-null  datetime64[ns]
 25  EnglishMonthName        114390 non-null  object
 26  CalendarYear            114390 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(9), object(11)
memory usage: 23.6+ MB

In [31]:
df_merge.head()

,ProductKey,OrderDateKey,CustomerKey,Gender_x,OrderNumber,OrderQuantity,List Price,Product Cost,GeographyKey,MaritalStatus,...,StandardCost,ListPrice,Product Name,ProductSubcategoryName,ProductCategoryKey,ProductCategoryName,DateKey,FullDateAlternateKey,EnglishMonthName,CalendarYear
0,344,20050722,11000,NaN,20061722,22,3399.99,1912.1544,26.0,M,...,1912.1544,3399.99,Product 89,Mountain Bikes,1,Bikes,20050722,2005-07-22,July,2005
1,353,20070722,11000,NaN,20081722,22,2319.99,1265.6195,26.0,M,...,1265.6195,2319.99,Product 94,Mountain Bikes,1,Bikes,20070722,2007-07-22,July,2007
2,485,20070722,11000,NaN,20081722,22,21.98,8.2205,26.0,M,...,8.2205,21.98,Product 163,Fenders,4,Accessories,20070722,2007-07-22,July,2007
3,530,20071104,11000,NaN,20082104,4,4.99,1.8663,26.0,M,...,1.8663,4.99,Product 208,Tires and Tubes,4,Accessories,20071104,2007-11-04,November,2007
4,214,20071104,11000,NaN,20082104,4,34.99,13.0863,26.0,M,...,13.0863,34.99,Product 3,Helmets,4,Accessories,20071104,2007-11-04,November,2007

In [32]:
df_merge.describe()

,ProductKey,OrderDateKey,CustomerKey,Gender_x,OrderNumber,OrderQuantity,List Price,Product Cost,GeographyKey,ProductSubcategoryKey,StandardCost,ListPrice,ProductCategoryKey,DateKey,FullDateAlternateKey,CalendarYear
count,114390.000000,1.143900e+05,114390.000000,0.0,1.143900e+05,114390.000000,114390.000000,114390.000000,63738.000000,114390.000000,114390.000000,114390.000000,114390.000000,1.143900e+05,114390,114390.000000
mean,437.478276,2.007530e+07,18286.348352,NaN,2.009359e+07,15.730641,477.332908,280.424035,230.952713,23.389457,280.424035,477.332908,3.099274,2.007530e+07,2007-12-14 01:33:45.554681344,2007.464656
min,214.000000,2.005070e+07,11000.000000,NaN,2.006170e+07,1.000000,2.290000,0.856500,2.000000,1.000000,0.856500,2.290000,1.000000,2.005070e+07,2005-07-01 00:00:00,2005.000000
25%,359.000000,2.007100e+07,13790.000000,NaN,2.008787e+07,8.000000,7.950000,2.973300,51.000000,3.000000,2.973300,7.950000,1.000000,2.007100e+07,2007-10-05 00:00:00,2007.000000
50%,479.000000,2.008012e+07,17656.000000,NaN,2.009427e+07,16.000000,29.990000,11.216300,215.000000,28.000000,11.216300,29.990000,4.000000,2.008012e+07,2008-01-15 00:00:00,2008.000000
75%,529.000000,2.008042e+07,22560.000000,NaN,2.009898e+07,23.000000,539.990000,294.579700,329.000000,37.000000,294.579700,539.990000,4.000000,2.008042e+07,2008-04-20 00:00:00,2008.000000
max,606.000000,2.008073e+07,28027.000000,NaN,2.010875e+07,31.000000,3578.270000,2171.294200,654.000000,37.000000,2171.294200,3578.270000,4.000000,2.008073e+07,2008-07-31 00:00:00,2008.000000
std,117.702277,6.241904e+03,5033.693815,NaN,8.247936e+03,8.772385,911.229190,541.203159,192.659076,13.539186,541.203159,911.229190,1.261029,6.241904e+03,NaN,0.646259

In [33]:
df_merge.groupby('CalendarYear')['List Price'].sum()

CalendarYear
2005    4.802202e+06
2006    1.210431e+07
2007    1.885701e+07
2008    1.883859e+07
Name: List Price, dtype: float64

In [34]:
df_merge.groupby('Region')['List Price'].sum()

Region
Alabama                7.458000e+01
Alberta                3.020431e+04
Arizona                6.520000e+01
Bayern                 4.479720e+05
Brandenburg            3.367508e+04
British Columbia       1.984727e+06
California             5.491047e+06
Charente-Maritime      2.851999e+04
England                3.894597e+06
Essonne                2.550056e+05
Garonne (Haute)        3.204450e+04
Georgia                3.317840e+03
Hamburg                4.734073e+05
Hauts de Seine         3.350623e+05
Hessen                 7.497718e+05
Illinois               2.544400e+02
Kentucky               4.339200e+02
Loir et Cher           2.152550e+04
Loiret                 1.023264e+05
Minnesota              1.825600e+02
Mississippi            1.651800e+02
Missouri               1.629200e+02
Montana                1.841600e+02
Moselle                1.062751e+05
New South Wales        3.731826e+06
New York               4.776420e+03
Nord                   4.292156e+05
Nordrhein-Westfalen    6.290728e+05
Ohio                   3.615000e+02
Oregon                 9.535074e+05
Pas de Calais          1.138397e+04
Queensland             1.786223e+06
Saarland               7.498550e+05
Seine (Paris)          5.581254e+05
Seine Saint Denis      3.391520e+05
Seine et Marne         1.070205e+05
Somme                  1.799052e+04
South Australia        4.730086e+05
Tasmania               1.817908e+05
Texas                  3.527240e+03
Val d'Oise             5.823148e+04
Val de Marne           1.822258e+04
Victoria               2.091223e+06
Washington             2.263677e+06
Wyoming                1.423002e+04
Yveline                1.978075e+05
Name: List Price, dtype: float64

In [35]:
df_merge.groupby(['CalendarYear','Region'])['List Price'].sum()

CalendarYear  Region
2005          Alberta                7156.5400
              Bayern                57252.3200
              British Columbia     176180.0656
              California           170200.0768
              Charente-Maritime      7156.5400
                                      ...
2008          Val de Marne           6376.6800
              Victoria             600766.9800
              Washington           950484.2200
              Wyoming                2428.9200
              Yveline               97305.6000
Name: List Price, Length: 147, dtype: float64

In [44]:
df_merge.pivot_table(index=['ProductCategoryName','Region'], values='List Price',columns=['Country'], aggfunc='sum')

Country                           Australia  Canada  France  Germany  \
ProductCategoryName Region
Accessories         Alabama             NaN     NaN     NaN      NaN
                    Alberta             NaN   460.4     NaN      NaN
                    Arizona             NaN     NaN     NaN      NaN
                    Bayern              NaN     NaN     NaN  8968.88
                    Brandenburg         NaN     NaN     NaN   641.62
...                                     ...     ...     ...      ...
Clothing            Val de Marne        NaN     NaN  418.86      NaN
                    Victoria       20792.24     NaN     NaN      NaN
                    Washington          NaN     NaN     NaN      NaN
                    Wyoming             NaN     NaN     NaN      NaN
                    Yveline             NaN     NaN  944.70      NaN

Country                           United Kingdom  United States
ProductCategoryName Region
Accessories         Alabama                  NaN          74.58
                    Alberta                  NaN            NaN
                    Arizona                  NaN          65.20
                    Bayern                   NaN            NaN
                    Brandenburg              NaN            NaN
...                                          ...            ...
Clothing            Val de Marne             NaN            NaN
                    Victoria                 NaN            NaN
                    Washington               NaN       41678.60
                    Wyoming                  NaN         117.96
                    Yveline                  NaN            NaN

[126 rows x 6 columns]

In [ ]:
df_merge.groupby(['CalendarYear','Region'])['List Price'].sum()

CalendarYear  Region
2005          Alberta                7156.5400
              Bayern                57252.3200
              British Columbia     176180.0656
              California           170200.0768
              Charente-Maritime      7156.5400
                                      ...
2008          Val de Marne           6376.6800
              Victoria             600766.9800
              Washington           950484.2200
              Wyoming                2428.9200
              Yveline               97305.6000
Name: List Price, Length: 147, dtype: float64

In [ ]:
df_merge.groupby(['CalendarYear','Region'])['List Price'].sum()

CalendarYear  Region
2005          Alberta                7156.5400
              Bayern                57252.3200
              British Columbia     176180.0656
              California           170200.0768
              Charente-Maritime      7156.5400
                                      ...
2008          Val de Marne           6376.6800
              Victoria             600766.9800
              Washington           950484.2200
              Wyoming                2428.9200
              Yveline               97305.6000
Name: List Price, Length: 147, dtype: float64

In [ ]:
df_merge.groupby(['CalendarYear','Region'])['List Price'].sum()

CalendarYear  Region
2005          Alberta                7156.5400
              Bayern                57252.3200
              British Columbia     176180.0656
              California           170200.0768
              Charente-Maritime      7156.5400
                                      ...
2008          Val de Marne           6376.6800
              Victoria             600766.9800
              Washington           950484.2200
              Wyoming                2428.9200
              Yveline               97305.6000
Name: List Price, Length: 147, dtype: float64

In [38]:
df_merge.groupby(['ProductCategoryName','Region'])[['OrderQuantity','List Price']].agg(['sum','mean','min','max'])

                                 OrderQuantity                    List Price  \
                                           sum       mean min max        sum
ProductCategoryName Region
Accessories         Alabama                 56  14.000000  13  15      74.58
                    Alberta                464  21.090909   7  30     460.40
                    Arizona                 10   5.000000   5   5      65.20
                    Bayern                6740  15.180180   1  31    8968.88
                    Brandenburg            522  13.736842   2  29     641.62
...                                        ...        ...  ..  ..        ...
Clothing            Val de Marne           204  14.571429   2  29     418.86
                    Victoria              8556  16.581395   1  31   20792.24
                    Washington           15002  14.942231   1  31   41678.60
                    Wyoming                 72  18.000000  18  18     117.96
                    Yveline                400  13.333333   5  24     944.70


                                       mean    min     max
ProductCategoryName Region
Accessories         Alabama       18.645000   2.29   35.00
                    Alberta       20.927273   2.29  120.00
                    Arizona       32.600000  32.60   32.60
                    Bayern        20.200180   2.29  159.00
                    Brandenburg   16.884737   3.99   34.99
...                                     ...    ...     ...
Clothing            Val de Marne  29.918571   8.99   53.99
                    Victoria      40.295039   8.99   69.99
                    Washington    41.512550   8.99   69.99
                    Wyoming       29.490000   8.99   49.99
                    Yveline       31.490000   8.99   53.99

[126 rows x 8 columns]

In [42]:
df_merge.pivot_table(index='ProductCategoryName',columns='EnglishMonthName',values='List Price',aggfunc=['sum','mean','min','max'])

                              sum                                           \
EnglishMonthName            April        August     December      February
ProductCategoryName
Accessories          1.197942e+05  9.982574e+04   125598.080  1.080796e+05
Bikes                5.299091e+06  3.311942e+06  5248559.628  4.484490e+06
Clothing             6.121030e+04  4.399752e+04    59323.740  5.311548e+04

                                                                             \
EnglishMonthName          January          July          June         March
ProductCategoryName
Accessories          1.079127e+05  9.362420e+04  1.212591e+05  1.157509e+05
Bikes                4.100607e+06  3.558445e+06  5.904980e+06  4.921854e+06
Clothing             5.641598e+04  4.521614e+04  6.581814e+04  5.524322e+04

                                                 ...      max           \
EnglishMonthName              May      November  ... December February
ProductCategoryName                              ...
Accessories          1.377764e+05  1.050222e+05  ...   159.00   159.00
Bikes                5.873967e+06  3.495321e+06  ...  3578.27  3578.27
Clothing             5.905402e+04  4.837206e+04  ...    69.99    69.99

                                                                           \
EnglishMonthName     January     July     June    March      May November
ProductCategoryName
Accessories           159.00   159.00   159.00   159.00   159.00   159.00
Bikes                3578.27  3578.27  3578.27  3578.27  3578.27  3578.27
Clothing               69.99    69.99    69.99    69.99    69.99    69.99


EnglishMonthName     October September
ProductCategoryName
Accessories           159.00    159.00
Bikes                3578.27   3578.27
Clothing               69.99     69.99

[3 rows x 48 columns]